@host = http://localhost:5125

@adminId = ad577f2a-bf03-432f-82e3-2aec057e3ec3

POST {{host}}/Subscriptions
Content-Type: application/json

{
    "SubscriptionType": "Free",
    "AdminId": "{{adminId}}"
}